version: '2'
services:
  zoo1:
    image: zookeeper:3.4.11
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_HOST_NAME=kafka
      - KAFKA_ADVERTISED_HOST=kafka
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  clickhouse:
    image: yandex/clickhouse-server:18
    depends_on:
      - zoo1
    ports:
      - "8123:8123"
      - "9000:9000"
  
  tabix:
      image: spoonest/clickhouse-tabix-web-client
      ports:
        - 8081:80

  build:
    image: javiersanz/go-kafka-talk:master
    volumes:
      - $PWD:/outOfGoPath
    command: bash
    stdin_open: true
    tty: true
    environment:
      - KAFKA_HOSTS=kafka:9092
     